language: node_js
node_js:
- v9.11.2
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  keyfile: client-secret.json
  provider: gae
  project: forum-front
  default: true
  docker-build: remote
  on:
    branches:    # ← new!
      only:      # ← new!
        - master # ← new!
true:
  branch: master
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_78ec74c37cd8_key -iv $encrypted_78ec74c37cd8_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar xvzf credentials.tar.gz 

email: false
